---
title: "mibitof"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
package: "`r BiocStyle::pkg_ver('SpatialData')`"
author:
- name: Helena L Crowell
  affiliation:
  - Department of Molecular Life Sciences, University of Zurich, Switzerland
  - SIB Swiss Institute of Bioinformatics, University of Zurich, Switzerland
- name: Constantin Ahlmann-Eltze
  affiliation: EMBL Genome Biology Unit, Heidelberg, Germany
- name: Tim Treis
  affiliation: Computational Health Center, Helmholtz Center Munich, Neuherberg, Germany
output: 
  BiocStyle::html_document:
    toc: true
    toc_depth: 2
# having some bug w/ basilisk/reticulate & this gets around it
knit: (function(input, ...) rmarkdown::render(input, output_dir=".")) 
vignette: >
  %\VignetteIndexEntry{"mibitof"}
  %\VignettePackage{SpatialData}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
abstract: > 
  <p> ...
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# Preamble

## Dependencies

```{r load-libs, message=FALSE, warning=FALSE}
library(tidyr)
library(ggplot2)
library(patchwork)
library(SpatialData)
library(SingleCellExperiment)
```

## Load data

```{r}
path <- file.path("..", "inst", "extdata", "mibitof")
(spd <- readSpatialData(path))
```

# Visualization

## Images

```{r plot-images, fig.width=10, fig.height=3.5}
ps <- lapply(images(spd), plotElement)
wrap_plots(ps, nrow = 1)
```

## Labels

```{r plot-labels, fig.width=10, fig.height=3.5}
ps <- lapply(labels(spd), plotElement)
wrap_plots(ps, nrow = 1)
```

## Layered

```{r plot-layers, fig.width=10, fig.height=3.5}
ps <- mapply(
    \(i, l) plotSD(spd, image = i, label = l),
    SIMPLIFY = FALSE, i = imageNames(spd), l = labelNames(spd))
wrap_plots(ps, nrow = 1)
```

# Aggregation

## Image by label

```{r calc-sce}
# TODO: one function call should aggregate
# across all matching coordinate systems
ms <- mapply(
    \(i, l) {
        sce <- aggregateImage(spd, image = i, label = l)
        sce$id <- i; return(sce)
    },
    SIMPLIFY = FALSE, i = imageNames(spd), l = labelNames(spd))
(sce <- do.call(cbind, ms))
```

## Visualization

```{r plot-sce, fig.width=9, fig.height=8}
chs <- rownames(sce) <- c("R", "G", "B")
df <- data.frame(colData(sce), t(assay(sce)), check.names = FALSE)
fd <- pivot_longer(df, all_of(chs))
fd$name <- factor(fd$name, chs)
ggplot(fd, aes(x, y, col = value)) +
    geom_point(size = 1) + facet_grid(id ~ name) +
    scale_color_viridis_c(option = "C", trans = "sqrt") +
    scale_y_reverse() + coord_equal() + 
    theme_linedraw() + theme(
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "black"),
        strip.background = element_rect(fill = "black", color = "white"))
```

# Appendix

## Session info

```{r session-info}
sessionInfo()
```
