---
title: "The `SpatialData` class"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
package: "`r BiocStyle::pkg_ver('SpatialData')`"
author:
- name: Constantin Ahlmann-Eltze
  affiliation: EMBL Genome Biology Unit, Heidelberg, Germany
- name: Helena L Crowell
  affiliation:
  - Department of Molecular Life Sciences, University of Zurich, Switzerland
  - SIB Swiss Institute of Bioinformatics, University of Zurich, Switzerland
- name: Tim Treis
  affiliation: Computational Health Center, Helmholtz Center Munich, Neuherberg, Germany
output: 
  BiocStyle::html_document:
    toc: true
    toc-depth: 2
    toc-float: true
# having some bug & this gets around it
knit: (function(input, ...) rmarkdown::render(input, output_dir=".")) 
vignette: >
  %\VignetteIndexEntry{"foo"}
  %\VignettePackage{foo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
#bibliography: "`r file.path(system.file('extdata', package='muscat'), 'refs.bib')`"
abstract: > 
  <p> ...
---

# Preamble

## Dependencies

```{r load-libs, message=FALSE, warning=FALSE}
library(Rarr)
library(EBImage)
library(ggplot2)
library(jsonlite)
library(SpatialData)
library(SingleCellExperiment)
```

## Introduction

# `ImageArray`

## Constructor

```{r load-data}
path <- system.file("extdata", "blobs", package="SpatialData", mustWork=TRUE)
zarr <- file.path(path, "images", "blobs_image")

za <- read_zarr_array(file.path(zarr, "0"))
md <- fromJSON(file.path(zarr, ".zattrs"))
(ia <- ImageArray(za, md))
```

## `readArray`

```{r}
(ia <- readArray(zarr))
```

# `SpatialData`

```{r}
(spd <- readSpatialData(path))
```

## Accessors

`SpatialData` objects behave like a list, i.e.,
Elements can be accessed in various (equivalent) ways:

```{r results="hide"}
i <- "blobs_image"
element(spd, "images", i)
images(spd)[[i]]
image(spd, i)
spd$images[[i]]
```

```{r}
(img <- image(spd))
(lab <- label(spd))
```

# Visualization

```{r}
path <- system.file("extdata", "raccoon", package="SpatialData", mustWork=TRUE)
(spd <- readSpatialData(path))
```

```{r}
plotSD(spd,
    iamge="raccoon",
    label="segmentation",
    shape="circles",
    alpha.label=1/3,
    alpha.shape=1,
    color.shape="lightgrey")
```

```{r}
# utility for image plotting with 'EBImage'
.plot <- \(i) {
    c <- ifelse(
        length(dim(i)) == 3, 
        "Color", "Grayscale")
    j <- as.array(aperm(i))
    plot(Image(j/max(j), dim(j), c))
}
par(mfrow=c(1,2))
.plot(img)
.plot(lab)
```

```{r}
(sce <- aggregateImage(spd))
col <- t(assay(sce))
rgb <- c("R", "G", "B")
colnames(col) <- rgb
cd <- do.call(rbind, lapply(rgb, \(.) 
    data.frame(colData(sce), z=col[, .], col=.)))
ggplot(cd, aes(x, y, col=z)) + 
    scale_color_viridis_c() + 
    scale_y_reverse() +
    facet_grid(~col) +
    geom_point() +
    coord_fixed()
```

# Transformations

```{r}
(i <- image(spd))
coords(i)
```

## `scaleImage`

```{r}
j <- scaleImage(i, c(1,1,2))
par(mfrow=c(1,2)); .plot(i); .plot(j)
```

## `rotateImage`

```{r}
j <- rotateImage(i, 30)
par(mfrow=c(1,2)); .plot(i); .plot(j)
```

# Appendix

## Session info

```{r session-info}
sessionInfo()
```
