xy <- c("x", "y")
require(sf, quietly=TRUE)
x <- file.path("extdata", "blobs.zarr")
x <- system.file(x, package="SpatialData")
x <- readSpatialData(x, tables=FALSE)

image(x, "x") <- flip(image(x, 2), k=1)
image(x, "y") <- flip(image(x, 2), k=3)
plotSpatialData() + plotImage(x, "x") +
plotSpatialData() + plotImage(x, "y") 

test_that("centroids,LabelArray", {
    y <- label(x)
    z <- centroids(y, "data.frame")
    expect_is(z, "data.frame")
    expect_identical(names(z), c(xy, "i"))
    expect_is(z$i, "factor")
    expect_is(unlist(z[xy]), "numeric")
    .z <- centroids(y, "matrix")
    expect_is(.z, "matrix")
    z$i <- as.integer(as.character(z$i))
    expect_identical(.z, as.matrix(z))
})
test_that("centroids,PointFrame", {
    i <- feature_key(y <- point(x))
    z <- centroids(y, "data.frame")
    expect_is(z, "data.frame")
    expect_identical(names(z), c(xy, i))
    expect_is(z[[i]], "factor")
    expect_is(unlist(z[xy]), "integer")
    .z <- centroids(y, "list")
    expect_is(.z, "list")
    expect_all_true(names(.z) %in% z[[i]])
    expect_length(.z, length(unique(z[[i]])))
    for (. in names(.z)) expect_identical(
        .z[[.]][xy], z[z[[i]] == ., xy])
})
test_that("centroids,ShapeFrame", {
    # circle
    y <- shape(x)
    z <- centroids(y, "data.frame")
    expect_is(z, "data.frame")
    expect_identical(names(z), xy)
    expect_is(unlist(z[xy]), "numeric")
    .z <- centroids(y, "matrix")
    expect_identical(.z, as.matrix(z))
    # polygon
    y <- shape(x, 3)
    z <- centroids(y, "data.frame")
    expect_is(z, "data.frame")
    expect_all_true(xy %in% names(z))
    expect_is(z[[ncol(z)]], "factor")
    expect_is(unlist(z[xy]), "numeric")
    .z <- centroids(y, "matrix")
    expect_is(.z, "matrix")
    expect_identical(.z[, xy], as.matrix(z[xy]))
    # multipolygon
    y <- shape(x, 2)
    z <- centroids(y, "data.frame")
    expect_is(z, "data.frame")
    expect_all_true(xy %in% names(z))
    expect_is(z[[ncol(z)]], "factor")
    expect_is(unlist(z[xy]), "numeric")
    .z <- centroids(y, "matrix")
    expect_is(.z, "matrix")
    for (. in seq(3, ncol(z)))
        z[[.]] <- as.integer(as.character(z[[.]]))
    expect_identical(.z, as.matrix(z))
})

test_that("extent,ImageArray", {
    z <- extent(y <- image(x)[,-1,-c(1,2)])
    expect_is(z, "list")
    expect_is(unlist(z), "numeric")
    expect_identical(names(z), rev(xy))
    expect_identical(z$y, c(0, dim(y)[2]))
    expect_identical(z$x, c(0, dim(y)[3]))
})
test_that("extent,LabelArray", {
    z <- extent(y <- label(x)[,-1,-c(1,2)])
    expect_is(z, "list")
    expect_is(unlist(z), "numeric")
    expect_identical(names(z), rev(xy))
    expect_identical(z$y, c(0, dim(y)[1]))
    expect_identical(z$x, c(0, dim(y)[2]))
})
test_that("extent,PointFraome", {
    z <- extent(y <- point(x))
    expect_is(z, "list")
    expect_identical(names(z), xy)
    expect_is(unlist(z), "integer")
    expect_identical(z$x, range(y$x))
    expect_identical(z$y, range(y$y))
})
test_that("extent,ShapeFrame", {
    z <- extent(y <- shape(x))
    expect_is(z, "list")
    expect_identical(names(z), xy)
    expect_is(unlist(z), "numeric")
    mx <- st_coordinates(st_as_sf(data(y)))
    expect_identical(z$x, range(mx[, 1]))
    expect_identical(z$y, range(mx[, 2]))
})
