xy <- c("x", "y")
x <- file.path("extdata", "blobs.zarr")
x <- system.file(x, package="SpatialData")
x <- readSpatialData(x, tables=FALSE)

test_that("centroids,LabelArray", {
    y <- label(x)
    z <- centroids(y, "data.frame")
    expect_is(z, "data.frame")
    expect_identical(names(z), c(xy, "i"))
    expect_is(z$i, "factor")
    expect_is(unlist(z[xy]), "numeric")
    .z <- centroids(y, "matrix")
    expect_is(.z, "matrix")
    z$i <- as.integer(as.character(z$i))
    expect_identical(.z, as.matrix(z))
})

test_that("centroids,PointFrame", {
    i <- feature_key(y <- point(x))
    z <- centroids(y, "data.frame")
    expect_is(z, "data.frame")
    expect_identical(names(z), c(xy, i))
    expect_is(z[[i]], "factor")
    expect_is(unlist(z[xy]), "integer")
    .z <- centroids(y, "list")
    expect_is(.z, "list")
    expect_all_true(names(.z) %in% z[[i]])
    expect_length(.z, length(unique(z[[i]])))
    for (. in names(.z)) expect_identical(
        .z[[.]][xy], z[z[[i]] == ., xy])
})

test_that("centroids,ShapeFrame", {
    # circle
    y <- shape(x)
    z <- centroids(y, "data.frame")
    expect_is(z, "data.frame")
    expect_identical(names(z), xy)
    expect_is(unlist(z[xy]), "numeric")
    .z <- centroids(y, "matrix")
    expect_identical(.z, as.matrix(z))
    # polygon
    y <- shape(x, 3)
    z <- centroids(y, "data.frame")
    expect_is(z, "data.frame")
    expect_all_true(xy %in% names(z))
    expect_is(z[[ncol(z)]], "factor")
    expect_is(unlist(z[xy]), "numeric")
    .z <- centroids(y, "matrix")
    expect_is(.z, "matrix")
    expect_identical(.z[, xy], as.matrix(z[xy]))
    # multipolygon
    y <- shape(x, 2)
    z <- centroids(y, "data.frame")
    expect_is(z, "data.frame")
    expect_all_true(xy %in% names(z))
    expect_is(z[[ncol(z)]], "factor")
    expect_is(unlist(z[xy]), "numeric")
    .z <- centroids(y, "matrix")
    expect_is(.z, "matrix")
    for (. in seq(3, ncol(z)))
        z[[.]] <- as.integer(as.character(z[[.]]))
    expect_identical(.z, as.matrix(z))
})
