## Visium

### preamble

```{r load-libs}
library(ggplot2)
library(scrapper)
library(patchwork)
library(SpatialData)
library(SpatialData.data)
library(SpatialData.plot)
library(SingleCellExperiment)
```

```{r load-data}
(sd <- MouseBrainVis())
```

### analysis

```{r fig.width=6, fig.height=5}
# TODO: low-res. images miss coordTrans altogether, 
# leading to failure; handle this case or fix data?

# TODO: HnE visualization seems broken; 
# needs fixing in SpatialData.plot

n <- length(s <- shape(sd))
shape(sd, "spots") <- s[sample(n, 333)]
cl <- rep(list(c(0, 1/3)), 3)
plotSpatialData() +  
    plotImage(sd, cl=cl) +
    plotShape(sd, "spots", col="red")
```

```{r fig.width=6, fig.height=3}
bb <- list(xmin=800, xmax=1600, ymin=500, ymax=900)
image(sd, "roi") <- crop(image(sd), bb)
shape(sd, "box") <- crop(shape(sd), bb)
plotSpatialData() +
    plotImage(sd, "roi", cl=cl) +
    plotShape(sd, "box", col="white", fill=NA)
```

```{r fig.width=12, fig.height=5}
(se <- tables(sd)[[1]])
plotSpatialData() + plotShape(sd, colour="array_col") +
plotSpatialData() + plotShape(sd, colour="Map2") +
plot_layout(nrow=1) & scale_colour_viridis_c()
```

```{r}
# perform standard processing:
# - log-library size normalization
# - highly variable gene selection
# - principal component analysis
# - shared-nearest neighbor graph construction
# - community detection using Leiden algorithm
assayNames(se) <- "counts"
se <- normalizeRnaCounts.se(se)
se <- chooseRnaHvgs.se(se)
se <- runPca.se(se, rowData(se)$hvg)
se <- clusterGraph.se(se, method="leiden", resolution=0.5)
base::table(se$clusters)
```

```{r}
# TODO: make 'getTable' search 'reducedDims' as well
pc <- reducedDim(se, "PCA")
colnames(pc) <- paste0("PC", seq_len(ncol(pc)))
colData(se) <- cbind(colData(se), pc)

# overwrite table in copy
sp <- sd; table(sp) <- se
```

```{r fig.width=9, fig.height=3.5}
# visualize PCs 1-3 spatially
lapply(head(colnames(pc), 3), \(.) {
    plotSpatialData() + 
        plotShape(sp, col=NA, fill=.) + ggtitle(.) +
        scale_fill_gradient2(low="blue", high="red")
    }) |> 
    wrap_plots(nrow=1) &
    theme(legend.position="none")
```

```{r fig.width=4, fig.height=3.5, fig.align="center"}
i <- "ST8059050"
plotSpatialData() + 
    plotShape(sp, i, col=NA, fill="clusters") + ggtitle(i) +
    scale_fill_manual(values=rainbow(nlevels(se$clusters)))
```

### appendix

::: {.callout-note icon=false, collapse=true}

### session

```{r sess-info}
sessionInfo()
```

:::
