## VisiumHD

### preamble

```{r load-libs}
library(sf)
library(ggplot2)
library(scrapper)
library(patchwork)
library(SpatialData)
library(SpatialData.data)
library(SpatialData.plot)
library(SingleCellExperiment)
```

```{r load-data}
(sd <- MouseIntestineVisHD())
```

### analysis

```{r}
# simplify element identifiers
pat <- "Visium_HD_Mouse_Small_Intestine_"
imageNames(sd) <- gsub(pat, "", imageNames(sd))
shapeNames(sd) <- gsub(pat, "bin_", shapeNames(sd))
sd
```

```{r}
# low-resolution image & shape
i <- grepv("lowres", imageNames(sd))
s <- grepv("_016um", shapeNames(sd))
```

```{r}
cl <- rep(list(c(0, 1/3)), 3) # contrasts
plotSpatialData() + plotImage(sd, i, cl=cl)
```

```{r}
# target coordinate space
ct <- "downscaled_lowres" 
# bounding box query
bb <- list(xmin=100, xmax=200, ymin=200, ymax=300)
# apply crop
sp <- crop(sd, bb, j=ct)
```

```{r}
# visualize gene counts spatially
um16 <- grep("16um", shapeNames(sp))
plotSpatialData() + # TODO: legend!
    plotImage(sp, i=i, j=ct, cl=cl) + 
    plotShape(sp, i=s, j=ct, fill="Cd74", col=NA) +
    scale_fill_gradientn(colors=rev(hcl.colors(9, "RdPu")))
```

```{r echo=-1, fig.height=4}
par(mar=c(0,0,0,0))
# rasterization
(ex <- extent(shape(sd, s), ct))
tri <- with(ex, rbind(
    c(x[1], y[1]),
    c(x[2], y[1]),
    c(x[2], y[2]),
    c(x[1], y[1]))
) |> list() |> st_polygon() |> st_sfc()
plot(hex <- st_make_grid(tri, cellsize=10, square=FALSE))
```

```{r}
# aggregate gene counts by bin
t <- ShapeFrame(st_sf(geometry=hex))
t <- addCT(t, name=ct, type="identity", data=NULL)
shape(sd, "hex") <- t
sq <- mask(sd, 
    i=s, j="hex", k=ct, 
    how="sum", name="hex_sum")
(sf <- tables(sq)[["hex_sum"]])
```

```{r}
# visualize binned counts spatially
plotSpatialData() +
    plotShape(sq, i="hex", j=ct, fill="Fabp2", col=NA) +
    scale_fill_gradientn(
        trans="log10", na.value="white",
        colors=rev(hcl.colors(9, "RdPu")))
```

```{r}
# perform standard processing:
# - log-library size normalization
# - highly variable gene selection
# - principal component analysis
# - shared-nearest neighbor graph construction
# - community detection using Leiden algorithm
t <- grepv("16", tableNames(sd))
se <- tables(sd)[[t]]
assayNames(se) <- "counts"
se <- normalizeRnaCounts.se(se)
se <- chooseRnaHvgs.se(se)
se <- runPca.se(se, rowData(se)$hvg)
se <- clusterGraph.se(se, method="leiden", resolution=0.5)
base::table(se$clusters)
```

```{r}
# TODO: make 'getTable' search 'reducedDims' as well
pc <- reducedDim(se, "PCA")
colnames(pc) <- paste0("PC", seq_len(ncol(pc)))
colData(se) <- cbind(colData(se), pc)

# overwrite table in copy
sp <- sd; table(sp, t) <- se
sp <- crop(sp, bb, j=ct)
```

```{r fig.width=9, fig.height=3.5}
# visualize PCs 1-3 spatially
lapply(head(colnames(pc), 3), \(.) {
    plotSpatialData() + ggtitle(.) +
        plotShape(sp, i=s, j=ct, col=NA, fill=.) + 
        scale_fill_gradient2(low="blue", high="red")
    }) |> 
    wrap_plots(nrow=1) &
    theme(legend.position="none")
```

```{r fig.width=8, fig.height=3.5, fig.align="center"}
# visualize histopathology & clusters side-by-side
# TODO: y-axis is off when plotting image alone?
plotSpatialData() + 
    plotImage(sp, i=i, j=ct, cl=cl) +
    theme(legend.position="none") +
plotSpatialData() + 
    plotShape(sp, i=s, j=ct, fill="clusters", col=NA) +
    scale_fill_manual(values=rainbow(nlevels(se$clusters)))
```

### appendix

::: {.callout-note icon=false, collapse=true}

### session

```{r sess-info}
sessionInfo()
```

:::
