## Xenium

### preamble

```{r load-libs}
library(sf)
library(dplyr)
library(ggplot2)
library(patchwork)
library(SpatialData)
library(SpatialData.data)
library(SpatialData.plot)
library(SingleCellExperiment)
```

```{r load-data}
(sd <- JanesickBreastXeniumRep1())
```

### analysis

```{r fig.width=12, fig.height=5}
sp <- crop(sd, list(xmin=17e3, xmax=20e3, ymin=13e3, ymax=14e3))
point(sp) <- mutate(point(sp) , nuc=as.logical(overlaps_nucleus))
plotSpatialData() + 
    plotImage(sp) +
    plotPoint(sp, size=0.2, n=2e4, col="nuc") +
    scale_color_manual(values=c("blue", "deeppink")) +
    plotShape(sp, col="cyan", fill=NA)
```

```{r}
# make table annotate boundaries
regions(tables(sd)[[1]]) <- "cell_boundaries"
```

```{r}
# bounding box crop
bb <- list(xmin=4e3, xmax=12e3, ymin=8e3, ymax=12e3)
(sp <- crop(sd, bb))
```

```{r fig.width=12, fig.height=5}
plotSpatialData() + 
    plotShape(sp, col=NA, fill="transcript_counts") +
    plotPoint(sp, size=0.2, n=2e4, key="EPCAM", col="red") +
    scale_fill_gradientn(colors=hcl.colors(9, "Roma"), trans="log10")
```

```{r}
ks <- c("CAFs", "Endothelial")
(sp <- query(sd, celltype_major %in% ks))
plotSpatialData() +
    plotShape(sp, size=0.2, colour="celltype_major") +
    guides(col=guide_legend(override.aes=list(size=2)))
```

### appendix

::: {.callout-note icon=false, collapse=true}

### session

```{r sess-info}
sessionInfo()
```

:::
